### ISSUE TITLE
统计结果不准

### ISSUE THREAD

**Issue by zwathz** [HDT3213/rdb#10]
对比其他工具，对同一个rdb文件分析，得出的结果相差太大，计算出的总大小情况如下：
1. 使用redis-rdb-tools：3849536069（bytes），和实际值比较接近
2. 使用本工具：1617817854（bytes），和实际值相差太大

**Comment by HDT3213** [comment]
我是用 object 序列化之后的大小估算的，让我看看咋整

**Comment by HDT3213** [comment]
你是在用 memory report 的结果估算加载后 redis 的内存占用吗？

**Comment by zwathz** [comment]
> 

是的，使用./rdb -c memory

**Comment by HDT3213** [comment]
我还真没有设想过这个场景。我这边有个已知的 bug 是 memory report 里面没有过滤已过期的 key, 但是这个 bug 不会导致偏少的情况。我先把手头的测试用例和 redis-rdb-tools 对一下， 看看内存占用是不是有很大的偏差

**Comment by zwathz** [comment]
> 

我觉得已过期的key也需要报告出来，毕竟我们是分析历史rdb文件，可以用来做keyde 过期时间分布统计

**Comment by jayddzjh** [comment]
是因为只统计了value，没统计key大小吗

**Comment by zwathz** [comment]
其实redis-rdb-tools统计hash和zset类型的key大小也是不准的（偏小不少）；string类型的和实际的比较接近

**Comment by HDT3213** [comment]
redis-rdb-tools 会估算加载后需要的指针等结构占用的内存，甚至会估算因内存对齐而被浪费的内存，我这边只统计了序列化之后的大小。估算不准可能是因为 redis 版本升级使得实际结构与 redis-rdb-tools 估算时采用的结构不一致

**Comment by zwathz** [comment]
> 

可以优化吗？这个值的准确性对分析内存还是很重要的，我对比了好几款工具，基本都有这个问题，阿里云的离线分析得出的结果基本和实际内存一致，速度也挺快，不知道他用的是哪个工具

**Comment by HDT3213** [comment]
为啥不试试把数据直接加载进 redis 里看实际内存消耗呢？ Redis  加载 3 GB的数据几乎是一瞬间的事

**Comment by zwathz** [comment]
> 为啥不试试把数据直接加载进 redis 里看实际内存消耗呢？ Redis 加载 3 GB的数据几乎是一瞬间的事

需要看每个key的内存占用，然后做些数据分析

**Comment by HDT3213** [comment]
8433635 里更新了内存占用的实现，估计还有很多细节问题很难算准。memory report 里面加了 encoding 和过期时间， 新增命令行参数 -no-expired  来控制是否过滤过期键
