### ISSUE TITLE
统计top n的大key有bug

### ISSUE THREAD

**Issue by jayddzjh** [HDT3213/rdb#11]
`
// Append new object into tree set
// time complexity: O(n*log(m)), n is number of redis object, m is heap capacity. m if far less than n
func (h *redisTreeSet) Append(x model.RedisObject) {
    // if heap is full && x.Size > minSize, then pop min
    if h.set.Size() == h.capacity {
        min := h.GetMin()
        if min.GetSize() < x.GetSize() {
            h.set.Remove(min)
            h.set.Add(x)
        }
    } else {
        h.set.Add(x)
    }
}

`

**Comment by HDT3213** [comment]
请描述具体问题

**Comment by HDT3213** [comment]
append 之前应该比较一下 x 和 h.min 的大小的

**Comment by HDT3213** [comment]
还早呢，内存占用可不好算

**Comment by HDT3213** [comment]
fixed in f4b5face

**Comment by jayddzjh** [comment]
辛苦，老哥是学生还是工作了，可以加个qq或者微信吗

**Comment by HDT3213** [comment]
hdt3213

**Comment by HDT3213** [comment]
微信也是 hdt3213
