### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by jimsoft1000** [HDT3213/rdb#13]
能否加上stream类型的支持

**Comment by HDT3213** [comment]
抱歉没注意到你的 issue, 看我什么时候有时间加一下

**Comment by jimsoft1000** [comment]
幸苦了，stream是5以后的版本有的新特性

**Comment by HDT3213** [comment]
Working in process: https://github.com/HDT3213/rdb/tree/feature/stream

**Comment by HDT3213** [comment]
released in v1.0.8
