### ISSUE TITLE
support rdb version 11

### ISSUE THREAD

**Issue by weedge** [HDT3213/rdb#21]
https://github.com/redis/redis/commit/4e472a1a7fc0dc2c7da2b48ac7342e9385b4f92a  https://github.com/dragonflydb/dragonfly/pull/1579 有支持的计划吧~？

**Comment by HDT3213** [comment]
我有空搞一下

**Comment by HDT3213** [comment]
@weedge 弄好了，看上去 RDB 11 是 7.2 版本还没 release 的功能
