### ISSUE TITLE
rdb文件version:10 解析到stream时遇到错误

### ISSUE THREAD

**Issue by codelife** [HDT3213/rdb#29]
rdb文件version:10 解析到stream时遇到错误, 以下是一些信息. 现有rdb数据结构里没有stream的数据结构. 如果有参考文档请标明下,十分感谢
`readStreamListPacks version: 2 encode: listpack
readStreamEntries: length: 60
readStreamEntries index: 0 header: [0 0 1 137 147 155 165 86 0 0 0 0 0 0 0 0]
readStreamEntries firstId:1690398598486-0  ms: 1690398598486, seq: 0
line132 count: 17
line137 deleted: 0
line144 : fieldNum0: 4
line158 : masterFieldNames: [app_id client_id status payload]
client_status:.ead stream item flag failed: $a0346185-50b5-4d47-b2c8-004d2694ec52�1 (2

account_id 866f3b913df14d472007941600001010:
statusONLINE:
port20083 is not a uint
client_status:.eam item flag110 failed: $a0346185-50b5-4d47-b2c8-004d2694ec52�1 (2

部分实际数据
`*********:6379> XRANGE client_status_stream 1690398598486-0 1690508095589-5
   1) 1) "1690398598486-0"
      2) 1) "app_id"
         2) "123456"
         3) "client_id"
         4) "ChAUnX10KZBleXxHWtxmLimDEAEY6dQgIN2YBigC"
         5) "status"
         6) "OFFLINE"
         7) "payload"
         8) "\x12$************************************\x18\xd6\xca\xee\x9c\x991 \xa0\x99\x02(\x042\rclient_status:.\n\naccount_id\x12 866f3b913df14d472007941600001010:\x11\n\x06status\x12\aOFFLINE"
   2) 1) "1690398600783-0"
      2) 1) "payload"
         2) "\x12$************************************\x18\xce\xdc\xee\x9c\x991 \xa0\x99\x02(\x042\rclient_status:.\n\naccount_id\x12 866f3b913df14d472007941600001010:\x10\n\x06status\x12\x06ONLINE:\r\n\x04port\x12\x0520083"
         3) "client_id"
         4) "ChAUnX10KZBleXxHWtxmLimDEAEY6dQgIN2YBigC"
         5) "app_id"
         6) "123456"
         7) "status"
         8) "ONLINE"
`

**Comment by HDT3213** [comment]
文档我周末更新一下，你用的是什么版本的 rdb ？ [v1.0.14](https://github.com/HDT3213/rdb/releases/tag/v1.0.14) 中修了一个看上去比较类似的 bug

**Comment by codelife** [comment]
我现在用的就是最新版[v1.0.14](https://github.com/HDT3213/rdb/releases/tag/v1.0.14)

**Comment by tanjiaxi** [comment]
应该就是数据里面有压缩数据的原因吧

**Comment by HDT3213** [comment]
> `readStreamListPacks version: 2 encode: listpack
readStreamEntries: length: 60
readStreamEntries index: 0 header: [0 0 1 137 147 155 165 86 0 0 0 0 0 0 0 0]
readStreamEntries firstId:1690398598486-0 ms: 1690398598486, seq: 0
line132 count: 17
line137 deleted: 0
line144 : fieldNum0: 4
line158 : masterFieldNames: [app_id client_id status payload]
client_status:.ead stream item flag failed: $a0346185-50b5-4d47-b2c8-004d2694ec52�1 (2

account_id 866f3b913df14d472007941600001010:
statusONLINE:
port20083 is not a uint
client_status:.eam item flag110 failed: $a0346185-50b5-4d47-b2c8-004d2694ec52�1 (2

这块内容是什么， 我没有看懂

**Comment by HDT3213** [comment]
这个地方挂了 [stream.go#158](https://github.com/HDT3213/rdb/blob/master/core/stream.go#L158)， 本来读完 master item 之后应该读消息的 flag 的，但是不知道为什么读到了其中一个字段的值。

能否在 stream.go 的 160 行前面加一行，把出错的那个 stream entry 打印出来：

```go
for i := int64(0); i < total; i++ {
  flag, err := dec.readListPackEntryAsInt(buf, cursor)
  if err != nil {
	  println(base64.StdEncoding.EncodeToString(buf))  // 加这一行，把出错的那个 stream entry 打印出来
	  return nil, fmt.Errorf("read stream item flag failed: %v", err)
  }
```

**Comment by codelife** [comment]
> 这个地方挂了 [stream.go#158](https://github.com/HDT3213/rdb/blob/master/core/stream.go#L158)， 本来读完 master item 之后应该读消息的 flag 的，但是不知道为什么读到了其中一个字段的值。
> 
> 能否在 stream.go 的 160 行前面加一行，把出错的那个 stream entry 打印出来：
> 
> ```go
> for i := int64(0); i < total; i++ {
>   flag, err := dec.readListPackEntryAsInt(buf, cursor)
>   if err != nil {
> 	  println(base64.StdEncoding.EncodeToString(buf))  // 加这一行，把出错的那个 stream entry 打印出来
> 	  return nil, fmt.Errorf("read stream item flag failed: %v", err)
>   }
> ```

cxAAANsAEQEAAQQBhmFwcF9pZAeJY2xpZW50X2lkCoZzdGF0dXMHh3BheWxvYWQIAAECAQABAAHyXYwBBKhDaEFVblgxMEtaQmxlWHhIV3R4bUxpbURFQUVZNmRRZ0lOMllCaWdDKYdPRkZMSU5FCOCFEiQ4MjU5MmZkNS02YjI0LTQzM2UtYjNiYy02MDg3MzMwNzI2MDUY1srunJkxIKCZAigEMg1jbGllbnRfc3RhdHVzOi4KCmFjY291bnRfaWQSIDg2NmYzYjkxM2RmMTRkNDcyMDA3OTQxNjAwMDAxMDEwOhEKBnN0YXR1cxIHT0ZGTElORQGHBwEAAcj5AgABBAGHcGF5bG9hZAjgkxIkZjhlMGU4M2MtMGE3OC00MTk4LWE4ZDAtNzYwMTQ1ODg2MTdkGM7c7pyZMSCgmQIoBDINY2xpZW50X3N0YXR1czouCgphY2NvdW50X2lkEiA4NjZmM2I5MTNkZjE0ZDQ3MjAwNzk0MTYwMDAwMTAxMDoQCgZzdGF0dXMSBk9OTElORToNCgRwb3J0EgUyMDA4MwGViWNsaWVudF9pZAqoQ2hBVW5YMTBLWkJsZVh4SFd0eG1MaW1ERUFFWTZkUWdJTjJZQmlnQymGYXBwX2lkB/JdjAEEhnN0YXR1cweGT05MSU5FBwwBAAHxl0ADAAEEAYZhcHBfaWQH8l2MAQSGc3RhdHVzB4ZPTkxJTkUHh3BheWxvYWQI4JMSJDU2YTJjMGI5LTRkY2MtNDUxMS1iZDc5LTU3Yzk3MDUxNWJhNBjsy++cmTEgoJkCKAQyDWNsaWVudF9zdGF0dXM6LgoKYWNjb3VudF9pZBIgODY2ZjNiOTEzZGYxNGQ0NzIwMDc5NDE2MDAwMDEwMTA6EAoGc3RhdHVzEgZPTkxJTkU6DQoEcG9ydBIFMjAwODMBlYljbGllbnRfaWQKqENoQVVuWDEwS1pCbGVYeEhXdHhtTGltREVBRVk2ZFFnSU4yWUJpZ0MpDAEAAfFdQgMAAQQBhmFwcF9pZAfyXYwBBIdwYXlsb2FkCOCTEiRkZTk4ZWFkMS0xOGM5LTQyODQtYTI2NS1jOTgwMTA5MGJkYjgYss/vnJkxIKCZAigEMg1jbGllbnRfc3RhdHVzOi4KCmFjY291bnRfaWQSIDg2NmYzYjkxM2RmMTRkNDcyMDA3OTQxNjAwMDAxMDEwOhAKBnN0YXR1cxIGT05MSU5FOg0KBHBvcnQSBTIwMDgzAZWJY2xpZW50X2lkCqhDaEFVblgxMEtaQmxlWHhIV3R4bUxpbURFQUVZNmRRZ0lOMllCaWdDKYZzdGF0dXMHhk9OTElORQcMAQAB8SlLAwABBAGJY2xpZW50X2lkCqhDaEFVblgxMEtaQmxlWHhIV3R4bUxpbURFQUVZNmRRZ0lOMllCaWdDKYdwYXlsb2FkCOCTEiQxMDFlNjcxMi1mZTEyLTQ0MTItOTEzOC01MmI5ZmYxMDZjY2IY/+DvnJkxIKCZAigEMg1jbGllbnRfc3RhdHVzOi4KCmFjY291bnRfaWQSIDg2NmYzYjkxM2RmMTRkNDcyMDA3OTQxNjAwMDAxMDEwOhAKBnN0YXR1cxIGT05MSU5FOg0KBHBvcnQSBTIwMDgzAZWGYXBwX2lkB/JdjAEEhnN0YXR1cweGT05MSU5FBwwBAAHyYEIBBAABBAGHcGF5bG9hZAjghRIkMThlZWQ1MjgtNjkzOS00MjQ4LTkzNzgtMWI2ZGIxMGMzZWVkGLXP85yZMSCgmQIoBDINY2xpZW50X3N0YXR1czouCgphY2NvdW50X2lkEiA4NjZmM2I5MTNkZjE0ZDQ3MjAwNzk0MTYwMDAwMTAxMDoRCgZzdGF0dXMSB09GRkxJTkUBh4ZhcHBfaWQH8l2MAQSGc3RhdHVzB4dPRkZMSU5FCIljbGllbnRfaWQKqENoQVVuWDEwS1pCbGVYeEhXdHhtTGltREVBRVk2ZFFnSU4yWUJpZ0MpDAEAAfLUYAEEAAEEAYljbGllbnRfaWQKqENoQVVuWDEwS1pCbGVYeEhXdHhtTGltREVBRVk2ZFFnSU4yWUJpZ0MphmFwcF9pZAfyXYwBBIZzdGF0dXMHhk9OTElORQeHcGF5bG9hZAjgkxIkODE0NTVlN2MtMjFmYS00ZTY1LTg2OTItZjM3MDVhMGRiMDExGKqM9JyZMSCgmQIoBDINY2xpZW50X3N0YXR1czouCgphY2NvdW50X2lkEiA4NjZmM2I5MTNkZjE0ZDQ3MjAwNzk0MTYwMDAwMTAxMDoQCgZzdGF0dXMSBk9OTElORToNCgRwb3J0EgUyMDA4MwGVDAEAAfIfEQIEAAEEAYZzdGF0dXMHh09GRkxJTkUIhmFwcF9pZAfyXYwBBIljbGllbnRfaWQKqENoQVVuWDEwS1pCbGVYeEhXdHhtTGltREVBRVk2ZFFnSU4yWUJpZ0Mph3BheWxvYWQI4IUSJDg1ODExZmY4LWY3YWYtNGJhOC1hNmY1LTk5NGUyOTZjNjBkMhj17PacmTEgoJkCKAQyDWNsaWVudF9zdGF0dXM6LgoKYWNjb3VudF9pZBIgODY2ZjNiOTEzZGYxNGQ0NzIwMDc5NDE2MDAwMDEwMTA6EQoGc3RhdHVzEgdPRkZMSU5FAYcMAQAB8gNOAgQAAQQBhmFwcF9pZAfyXYwBBIZzdGF0dXMHhk9OTElORQeJY2xpZW50X2lkCqhDaEFVblgxMEtaQmxlWHhIV3R4bUxpbURFQUVZNmRRZ0lOMllCaWdDKYdwYXlsb2FkCOCTEiRhMDM0NjE4NS01MGI1LTRkNDctYjJjOC0wMDRkMjY5NGVjNTIY2Ob3nJkxIKCZAigEMg1jbGllbnRfc3RhdHVzOi4KCmFjY291bnRfaWQSIDg2NmYzYjkxM2RmMTRkNDcyMDA3OTQxNjAwMDAxMDEwOhAKBnN0YXR1cxIGT05MSU5FOg0KBHBvcnQSBTIwMDgzAZUMAQIB8lxaAwQAAfJdjAEEqENoQVVuWDEwS1pCbGVYeEhXdHhtTGltREVBRVk2ZFFnSU4yWUJpZ0Mph09GRkxJTkUI4IUSJGM0MzhjMDY3LTQyOWYtNGE4MC04M2YwLTMwYjEwY2NkZTIwOBiy//ucmTEgoJkCKAQyDWNsaWVudF9zdGF0dXM6LgoKYWNjb3VudF9pZBIgODY2ZjNiOTEzZGYxNGQ0NzIwMDc5NDE2MDAwMDEwMTA6EQoGc3RhdHVzEgdPRkZMSU5FAYcHAQAB8lnMFgQAAQQBhnN0YXR1cweGT05MSU5FB4dwYXlsb2FkCOCTEiQxMzU3ZDU4MS0zNDYxLTQ3ZGYtOGU2MS1kZTI3MDcyYzVhNmUYruPJnZkxIKCZAigEMg1jbGllbnRfc3RhdHVzOi4KCmFjY291bnRfaWQSIDg2NmYzYjkxM2RmMTRkNDcyMDA3OTQxNjAwMDAxMDEwOhAKBnN0YXR1cxIGT05MSU5FOg0KBHBvcnQSBTIwMDgzAZWJY2xpZW50X2lkCqhDaEFVblgxMEtaQmxlWHhIV3R4bUxpbURFQUVZNmRRZ0lOMllCaWdDKYZhcHBfaWQH8l2MAQQMAQAB8iEZGQQAAQQBiWNsaWVudF9pZAqoQ2hBVW5YMTBLWkJsZVh4SFd0eG1MaW1ERUFFWTZkUWdJTjJZQmlnQymGc3RhdHVzB4dPRkZMSU5FCIdwYXlsb2FkCOCFEiRiOTc4MDM3Ny1lNmJjLTRkMTQtODhhYS0yNWE0NDg5ZTRiMjgY9vzSnZkxIKCZAigEMg1jbGllbnRfc3RhdHVzOi4KCmFjY291bnRfaWQSIDg2NmYzYjkxM2RmMTRkNDcyMDA3OTQxNjAwMDAxMDEwOhEKBnN0YXR1cxIHT0ZGTElORQGHhmFwcF9pZAfyXYwBBAwBAAHyK/ggBAABBAGHcGF5bG9hZAjgkxIkMDcyMjJhNzQtYTI5Yy00Zjg2LWIzY2QtZDgzYmQzYzkwYTNhGP+68p2ZMSCgmQIoBDINY2xpZW50X3N0YXR1czouCgphY2NvdW50X2lkEiA4NjZmM2I5MTNkZjE0ZDQ3MjAwNzk0MTYwMDAwMTAxMDoQCgZzdGF0dXMSBk9OTElORToNCgRwb3J0EgUyMDA4MwGVhnN0YXR1cweGT05MSU5FB4ljbGllbnRfaWQKqENoQVVuWDEwS1pCbGVYeEhXdHhtTGltREVBRVk2ZFFnSU4yWUJpZ0MphmFwcF9pZAfyXYwBBAwBAAHyUO4hBAABBAGHcGF5bG9hZAjghRIkNWYzMTgwM2UtNDI0Yy00ZDM3LTliYzctYjVjNjBiMWFlMzJlGKan9p2ZMSCgmQIoBDINY2xpZW50X3N0YXR1czouCgphY2NvdW50X2lkEiA4NjZmM2I5MTNkZjE0ZDQ3MjAwNzk0MTYwMDAwMTAxMDoRCgZzdGF0dXMSB09GRkxJTkUBh4ZhcHBfaWQH8l2MAQSJY2xpZW50X2lkCqhDaEFVblgxMEtaQmxlWHhIV3R4bUxpbURFQUVZNmRRZ0lOMllCaWdDKYZzdGF0dXMHh09GRkxJTkUIDAEAAfLS/igEAAEEAYZzdGF0dXMHhk9OTElORQeHcGF5bG9hZAjgkxIkZmM5MTk4ZjEtZWE3ZS00NmMzLTk0YzMtYTVjY2NiN2NiNDdiGKfIkp6ZMSCgmQIoBDINY2xpZW50X3N0YXR1czouCgphY2NvdW50X2lkEiAxNDRlNWY4OTlkNjU0Y2UxMDE3NjIzOTAyMDAwMTAxMDoQCgZzdGF0dXMSBk9OTElORToNCgRwb3J0EgUyMDA4MwGViWNsaWVudF9pZAqoQ2hBSWs0MjVJUU5rOUsyNVFfUW1mLUpZRUFFWWk5UWdJTjJZQmlnQymGYXBwX2lkB/JdjAEEDAEAAfKhISkEAAEEAYljbGllbnRfaWQKqENoQUlrNDI1SVFOazlLMjVRX1FtZi1KWUVBRVlpOVFnSU4yWUJpZ0MphmFwcF9pZAfyXYwBBIZzdGF0dXMHh09GRkxJTkUIh3BheWxvYWQI4IUSJDEzNjU3MTExLWJiN2UtNGRiNC1iNWRhLWU1ODJjN2UwOWNlOBj1jZOemTEgoJkCKAQyDWNsaWVudF9zdGF0dXM6LgoKYWNjb3VudF9pZBIgMTQ0ZTVmODk5ZDY1NGNlMTAxNzYyMzkwMjAwMDEwMTA6EQoGc3RhdHVzEgdPRkZMSU5FAYcMAQAB8gvmKgQAAQQBh3BheWxvYWQI4JMSJDQzZTU1M2ZhLTQxMTMtNDljZS1iMzcwLTUzM2FmOTg3M2ZhMRjglpqemTEgoJkCKAQyDWNsaWVudF9zdGF0dXM6LgoKYWNjb3VudF9pZBIgODY2ZjNiOTEzZGYxNGQ0NzIwMDc5NDE2MDAwMDEwMTA6EAoGc3RhdHVzEgZPTkxJTkU6DQoEcG9ydBIFMjAwODMBlYZzdGF0dXMHhk9OTElORQeJY2xpZW50X2lkCqhDaEFVblgxMEtaQmxlWHhIV3R4bUxpbURFQUVZNmRRZ0lOMllCaWdDKYZhcHBfaWQH8l2MAQQMAf8=
client_status:.ead stream item flag failed: $a0346185-50b5-4d47-b2c8-004d2694ec52�1 (2

account_id 866f3b913df14d472007941600001010:
statusONLINE:
port20083 is not a uint
client_status:.eam item flag failed: $a0346185-50b5-4d47-b2c8-004d2694ec52�1 (2

account_id 866f3b913df14d472007941600001010:
statusONLINE:
port20083 is not a uint

**Comment by codelife** [comment]
有思路吗,需要我这边打印更多日志吗

**Comment by HDT3213** [comment]
我把出错的 listpack 中的元素都打出来了， 肉眼看上去 line15 及之前都是正常的， 从 line16 开始就乱了

```
line1: 17  // msg count
line2: 0   // deleted
line3: 4  // master field count
line4: app_id
line5: client_id
line6: status
line7: payload   
line8: 0 // master entry end 
line9: 2 // msg1 flag
line10: 0 // msg1 ms
line11: 0 // msg1 seq
line12: 101469 // msg1 app_id
line13: ChAUnX10KZBleXxHWtxmLimDEAEY6dQgIN2YBigC // msg1 client_id
line14: OFFLINE // msg1 status
line15: $82592fd5-6b24-433e-b3bc-608733072605��1 ��(2
client_status:.account_id 866f3b913df14d472007941600001010:statusOFFLINE // msg1 payload
line16:  // 应该是 msg1 的 lp_count 字段，数字 7。实际上是 0x87 长度小于64的短字符串
line17: 1 // msg2 flag
line18: 1 // msg2 ms
line19: 97 // msg2 seq 
line20: 108 // 这里应该是 msg2 的字段数，但是看起来后面都乱掉了
line21: 97
line22: 8
line23: 36
line24: 56
line25: 48
line26: 56
line27: 99
line28: 48
line29: 55
line30: 45
line31: 49
line32: 56
line33: 97
line34: 100
line35: 45
line36: 54
line37: 49
line38: 53
line39: 56
line40: 49
line41: 100
line42: 3804
line43: 32
line44: 40
line45: 50
```

**Comment by HDT3213** [comment]
能不能试着重新 save 一下或者用 redis-check-rdb 工具检查一下 rdb 文件是否正常

**Comment by codelife** [comment]
[offset 0] Checking RDB file /opt/homebrew/var/db/redis/dump.rdb
[offset 26] AUX FIELD redis-ver = '7.0.4'
[offset 40] AUX FIELD redis-bits = '64'
[offset 52] AUX FIELD ctime = '1706013279'
[offset 73] AUX FIELD used-mem = '2219099392'
[offset 85] AUX FIELD aof-base = '0'
[offset 87] Selecting DB ID 0
[offset 674890825] Selecting DB ID 1
[offset 735259375] Selecting DB ID 2
[offset 738011321] Selecting DB ID 4
[offset 738168857] Selecting DB ID 6
[offset 741207908] Selecting DB ID 9
[offset 741213113] Selecting DB ID 11
[offset 741228898] Selecting DB ID 12
[offset 741244309] Selecting DB ID 15
[offset 797580849] Checksum OK
[offset 797580849] \o/ RDB looks OK! \o/
[info] 1313395 keys read
[info] 109 expires
[info] 0 already expired

**Comment by HDT3213** [comment]
@codelife listpack 的 backlen 解析有问题， 已经修复了，等我晚上发个包

**Comment by codelife** [comment]
可以了, 非常感谢!!

我有一个疑问, 代码里面引入的package使用的是 "github.com/hdt3213/rdb/helper" 本地调试修改是往往不生效.这样做优点是什么. 请教下你这边的开发工作流是什么样的.再次感谢!!

`package main

import (
	"flag"
	"fmt"
	"localrdb/helper"
	"os"
	"strings"
)

const help = `
This is a tool to parse Redis' RDB files
Options:
  -c command, including: json/memory/aof/bigkey/flamegraph/prefix_summary
  -o output file path
  -n number of result, using in 
  -port listen port for flame graph web service
  -sep separator for flamegraph, rdb will separate key by it, default value is ":". 
		supporting multi separators: -sep sep1 -sep sep2 
  -regex using regex expression filter keys
  -no-expired filter expired keys


Examples:
parameters between '[' and ']' is optional
1. convert rdb to json
  rdb -c json -o dump.json dump.rdb
2. generate memory report
  rdb -c memory -o memory.csv dump.rdb
3. convert to aof file
  rdb -c aof -o dump.aof dump.rdb
4. get largest keys
  rdb -c bigkey [-o dump.aof] [-n 10] dump.rdb
5. draw flamegraph
  rdb -c flamegraph [-port 16379] [-sep :] dump.rdb
6. get summary size of keys with prefix
  rdb -c prefix_summary -o dump.csv -prefix_keys "prefix1,prefix2" dump.rdb
`

**Comment by HDT3213** [comment]
呃，我还没有碰到过不生效的情况。有可能是你的断点设在工作区里，但是实际执行的时候运行的是 GOPATH 目录下的代码。

有几种做法可以试试：
1.  clone 当前仓库，直接修改并调试 clone 下来的代码
2. 新建一个项目，import rdb, 然后利用 IDE 的「查找实现」功能找到实际调用的代码。或者按住 Command 键点击函数名也能跳转到函数实现。
3. 新建一个项目，import rdb，在调用 rdb 的地方下断点，然后单步进入也可以跳转到函数实现

工作流的话，常规的 github 做法。
1. fork 本仓库
2. 在 fork 出的仓库上提交代码
3. 向本仓库发出 pull request

代码需要经过 go fmt, 并遵循 go 的 code style. 一些不合适的写法我会在 code review 中提出来的。
一个功能一个 commit, 提 pull request 之前请先把提交 squash 一下。
