### ISSUE TITLE
自定义报表生成

### ISSUE THREAD

**Issue by zergduan** [HDT3213/rdb#31]
非常感谢您提供的工具，我想请教一下报表内容是否可以实现？
我希望通过读取RDB（或者连接Redis实例）得到以下报表：
表头如下：
Key前缀，Key数量，占用内存大小，未设置TTL的Key数量

我们通过Key前缀来区分不同服务，所以我需要以上内容来统计每种服务使用Redis是否规范。
请问以当前此工具提供的功能，是否可以自定义此报表的生成？
谢谢

**Comment by HDT3213** [comment]
我这两天正在写前缀树，不过能做完最早也是下周的事情了。

如果您能够用 strings.split 之类的方法找到前缀的话可以通过 decoder 二次开发或者分析导出的 json 文件之类的方式自己实现一个报表。

[自定义用途](https://github.com/HDT3213/rdb/blob/master/README_CN.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%94%A8%E9%80%94)

[rdb转json](https://github.com/HDT3213/rdb/blob/master/README_CN.md#%E8%BD%AC%E6%8D%A2%E4%B8%BA-json-%E6%A0%BC%E5%BC%8F)

**Comment by zergduan** [comment]
感谢您的回复~

**Comment by HDT3213** [comment]
前缀分析已经发布 [v1.0.16](https://github.com/HDT3213/rdb/releases/tag/v1.0.16)
