### ISSUE TITLE
遇到了一个错误 cursor out of range

### ISSUE THREAD

**Issue by BigChaoChao** [HDT3213/rdb#32]
定位了一下，发现是在decoder某个key时，出现的异常。 
补充一下具体信息：flag=18 ，typeListQuickList2，readQuickList2

该key为list类型，LLEN=624

**Comment by HDT3213** [comment]
请问， 您使用的 rdb 工具版本和 rdb 文件的版本是什么呢？

之前修过一个相关的 bug: #28

**Comment by BigChaoChao** [comment]
> 请问， 您使用的 rdb 工具版本和 rdb 文件的版本是什么呢？
> 
> 之前修过一个相关的 bug: #28

RDB可能是11，7.0的版本。 工具版本应该在这个bugfix之前了。代码看起来有些许关联，这就尝试更新一下！

**Comment by BigChaoChao** [comment]
> 请问， 您使用的 rdb 工具版本和 rdb 文件的版本是什么呢？
> 
> 之前修过一个相关的 bug: #28

更新到最新版本，确实已经解决了这个问题，感谢！
