### ISSUE TITLE
出现了OOM的情况，请教内存的占用情况

### ISSUE THREAD

**Issue by BigChaoChao** [HDT3213/rdb#33]
请教一个问题，内存的占用和释放是如何处理的，譬如分析一个10G的RDB需要占用多少内存呢？

在使用过程中出现过OOM的情况，当时遭遇了一个400MB的HashKey。

**Comment by HDT3213** [comment]
内存管理是按照 key 来做的，因为不同的编码格式之间差距很大，做的更细比较困难。

内存消耗和任务类型也有关，比如火焰图和toJson的内存消耗就很大，toAOF 和 memory profile 就会小一些

**Comment by HDT3213** [comment]
内存占用和文件大小关系不大， 但是大 key 很可能导致内存不足

**Comment by BigChaoChao** [comment]
好的，了解了。
