### ISSUE TITLE
Encoder uses incorrect version in header

### ISSUE THREAD

**Issue by nerg4l** [HDT3213/rdb#34]
The encoder currently uses a predefined header which contains 0003 in the version part of the header. However, it implements features that were added in later versions, like Aux data and crc64 checksum.

https://github.com/HDT3213/rdb/blob/d16ee7797e5f2d00be381c2b1981a52090a29ab9/core/encoder.go#L150

**Comment by HDT3213** [comment]
"REDIS0005" looks good for me

**Comment by HDT3213** [comment]
@nerg4l fixed in e9eadea, please verify it before I could release a new version

**Comment by nerg4l** [comment]
@HDT3213, sorry for not responding earlier.

The encoder can write Aux data which was added in version 7 based on https://github.com/sripathikrishnan/redis-rdb-tools/blob/master/docs/RDB_Version_History.textile. Based on this, I would recommend using at least version 7 in the header. This should depend on the latest OpCode but the simplest would be to write the biggest version supported by the decoder (12 at the moment).

**Comment by HDT3213** [comment]
I am worried that the rdb file format generated by this program is too old (for example, QuickList2 has replaced QuickList in RDB12, but this program still uses QuickList). But you are right, considering the compatibility of RDB, this is not a problem.

**Comment by HDT3213** [comment]
updated in f65fe74

Although many people are using my decoder, only few people are using the encoder😂

**Comment by nerg4l** [comment]
I'm using the encoder to filter out some values from an RDB and I'm also using it to validate the functionality of an RDB tokenizer I'm working on.

I really appreciate your work on this library.
