### ISSUE TITLE
想问一下是否支持通过远程连接redis分析内存呢？

### ISSUE THREAD

**Issue by wellslai** [HDT3213/rdb#41]
如题，感谢楼主的代码付出，没有的话就自己包装啦

**Comment by HDT3213** [comment]
现在还不支持。你是无法登录 redis 部署的服务器拿到 rdb 文件吗？

**Comment by wellslai** [comment]
> 

主要是线上有两千多套redis，想平台化操作 如果能远程分析，这样就可以把程序放在一台机器上分析了

**Comment by HDT3213** [comment]
emm，比较容易实现的方案是在脚本里写个 scp 命令把 rdb 拷贝过来。

另外一种麻烦的做法是在分析的机器上起一个 redis-server，通过 slaveof 命令设为从库从而获得 rdb 文件，不过这种做法会比较费时间

**Comment by HDT3213** [comment]
我这里倒是有一套模拟 redis 从库的代码，这个要接起来就更费时间了

**Comment by wellslai** [comment]
> 我这里倒是有一套模拟 redis 从库的代码，这个要接起来就更费时间了

哦 好吧 这个我自己包装下好了 感谢感谢
