### ISSUE TITLE
生成json文件只生成了一小部分

### ISSUE THREAD

**Issue by Yuz-lab** [HDT3213/rdb#43]
解析一个700mb的rdb文件，有800万个key
使用-c json后瞬间就完成了，没有报错，查看.json文件只有2000左右个key，然后json结构不完整，没有最后一行的“]”
使用-no-expried和-regex同样如此
请问可能是什么原因呢？
redis版本3.2.10 rdb版本7

**Comment by HDT3213** [comment]
应该是解析某个 key 的时候 panic 了。有没有输出日志？是否方便提供一下 rdb 文件？
